[package]
name = "thread_pool"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"

[dev-dependencies]
criterion = "0.5"
threadpool = "1.8.1"
rayon = "1.11.0"

[[bench]]
name = "main" # benchmark 的名字，可以任意取
harness = false
